import assert from 'node:assert/strict'
import {spawn} from 'node:child_process'
import {readFileSync,mkdtempSync,writeFileSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join,resolve} from 'node:path'
import {initializeTestEnvironment} from '@firebase/rules-unit-testing'
import {doc,getDoc,setDoc,deleteDoc} from 'firebase/firestore'

// All identities, content and uploads in this test exist only in local emulators.
const projectId='demo-freeride'
const environment=await initializeTestEnvironment({projectId,firestore:{rules:readFileSync('firebase/firestore.rules','utf8')},storage:{rules:readFileSync('firebase/storage.rules','utf8')}})
const temporaryDirectory=mkdtempSync(join(tmpdir(),'freeride-admin-test-'))
const backend=spawn(process.execPath,['-e',"require('firebase-admin').initializeApp({projectId:'demo-freeride'});require('./dist/app').default.listen(14002,'127.0.0.1')"],{cwd:resolve('../backend'),env:{...process.env,FIREBASE_AUTH_EMULATOR_HOST:'127.0.0.1:9099',FIRESTORE_EMULATOR_HOST:'127.0.0.1:8080'},stdio:'inherit'})
const vite=spawn(process.execPath,['node_modules/vite/bin/vite.js','--host','127.0.0.1','--port','5187','--strictPort'],{env:{...process.env,VITE_MAPBOX_ACCESS_TOKEN:process.env.VITE_MAPBOX_ACCESS_TOKEN ?? '',VITE_FIREBASE_API_KEY:'demo-api-key',VITE_FIREBASE_AUTH_DOMAIN:'demo-freeride.firebaseapp.com',VITE_FIREBASE_PROJECT_ID:projectId,VITE_FIREBASE_STORAGE_BUCKET:'demo-freeride.appspot.com',VITE_FIREBASE_APP_ID:'demo-app-id',VITE_FIREBASE_EMULATORS:'true',VITE_API_BASE_URL:'http://127.0.0.1:14002'},stdio:'ignore'})
const chrome=spawn(process.env.CHROME_BIN ?? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--disable-gpu','--no-first-run','--remote-debugging-port=9248',`--user-data-dir=${temporaryDirectory}`,'about:blank'],{stdio:'ignore'})
let socket
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms))
const poll=async (operation,message)=>{for(let i=0;i<100;i++){try{const result=await operation();if(result)return result}catch{}await wait(100)}throw new Error(message)}
try {
  await poll(async()=>{const response=await fetch('http://127.0.0.1:14002/');return response.ok},'Backend did not start')
  await environment.clearFirestore()
  const createUser=async email=>{
    const response=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signUp?key=demo-api-key',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password:'Test-password-123',returnSecureToken:true})})
    const result=await response.json();assert.ok(result.localId,JSON.stringify(result));return result.localId
  }
  const suffix=Date.now()
  const ownerEmail=`owner-${suffix}@example.com`,editorEmail=`editor-${suffix}@example.com`
  const ownerUid=await createUser(ownerEmail),editorUid=await createUser(editorEmail)
  await environment.withSecurityRulesDisabled(async context=>{const database=context.firestore();await setDoc(doc(database,'owners',ownerUid),{})})
  await poll(async()=>{const response=await fetch('http://127.0.0.1:5187/');return response.ok},'Vite did not start')
  const tabs=await poll(async()=>{const response=await fetch('http://127.0.0.1:9248/json/list');const data=await response.json();return data.find(tab=>tab.type==='page')},'Chrome did not start')
  socket=new WebSocket(tabs.webSocketDebuggerUrl)
  let nextId=1
  const pending=new Map(),errors=[]
  socket.onmessage=({data})=>{const event=JSON.parse(data);if(event.method==='Runtime.exceptionThrown')errors.push(event.params.exceptionDetails.text);if(event.id&&pending.has(event.id)){const {resolve,reject}=pending.get(event.id);pending.delete(event.id);event.error?reject(new Error(JSON.stringify(event.error))):resolve(event.result)}}
  await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject})
  const send=(method,params={})=>new Promise((resolve,reject)=>{const id=nextId++;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}))})
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw new Error(result.exceptionDetails.text);return result.result.value}
  const until=async expression=>{try{return await poll(()=>evaluate(expression),`Browser condition failed: ${expression}`)}catch(error){console.log('Browser state:',await evaluate("JSON.stringify({path:location.pathname,text:document.querySelector('main')?.innerText.slice(0,700)})"));throw error}}
  const clickText=async (selector,text)=>evaluate(`[...document.querySelectorAll(${JSON.stringify(selector)})].find(el=>el.textContent.trim()===${JSON.stringify(text)}).click()`)
  const fill=async (selector,value)=>evaluate(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});const prototype=el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(prototype,'value').set.call(el,${JSON.stringify(value)});el.dispatchEvent(new Event('input',{bubbles:true}))})()`)
  const navigate=async path=>{await send('Page.navigate',{url:`http://127.0.0.1:5187${path}`});await until("!!document.querySelector('main')")}
  const login=async email=>{await navigate('/login');await until("!!document.querySelector('input[type=email]')");await fill('input[type=email]',email);await fill('input[type=password]','Test-password-123');await evaluate("document.querySelector('form').requestSubmit()");await until("document.body.innerText.includes('Ви увійшли як')")}
  await send('Runtime.enable');await send('Page.enable')
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false})
  await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]})
  const mapboxConfigured=!!process.env.VITE_MAPBOX_ACCESS_TOKEN?.startsWith('pk.')
  const mapReady=mapboxConfigured ? "document.querySelector('.track-map-frame')?.dataset.mapState==='ready'" : "document.querySelector('.track-map-frame')?.dataset.mapState==='unconfigured'"
  await navigate('/events/freeride-carpathians')
  await until(mapReady)
  assert.ok(await evaluate("document.body.innerText.includes('Демонстраційний маршрут')"))
  await evaluate("document.querySelector('.track-map').scrollIntoView({block:'center'})")
  if(mapboxConfigured)assert.equal(await evaluate("document.querySelectorAll('.route-map-marker').length"),2)
  await wait(600)
  const mapShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})
  writeFileSync(join(temporaryDirectory,'demo-route.png'),Buffer.from(mapShot.data,'base64'))
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true})
  await until("document.querySelector('.track-map').getBoundingClientRect().width<390")
  assert.equal(await evaluate("document.documentElement.scrollWidth>window.innerWidth"),false)
  if(mapboxConfigured)await clickText('.track-map-toolbar button','Показати весь маршрут ↗')
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false})
  await navigate('/events/day-off-piste')
  await until(mapReady)
  assert.equal(await evaluate("document.querySelector('.route-description').textContent"),'Свидовець · район Драгобрата')
  console.log(mapboxConfigured ? 'PASS: Mapbox 3D routes load with endpoints on desktop/mobile' : 'PASS: missing Mapbox token shows setup state on desktop/mobile; report routes differ')
  await navigate('/login')
  await until("!!document.querySelector('input[type=email]')")
  const loginShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})
  writeFileSync(join(temporaryDirectory,'login.png'),Buffer.from(loginShot.data,'base64'))
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true})
  assert.equal(await evaluate("document.documentElement.scrollWidth>window.innerWidth"),false)
  const loginMobileShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})
  writeFileSync(join(temporaryDirectory,'login-mobile.png'),Buffer.from(loginMobileShot.data,'base64'))
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false})
  await login(ownerEmail)
  await clickText('a','Відкрити адмін-панель →')
  await until("!!document.querySelector('.admin-sidebar')")
  await fill('.admin-panel textarea:nth-of-type(1)','ГОРИ КЛИЧУТЬ ДАЛІ')
  await fill('.admin-panel label:nth-of-type(2) textarea','Тестовий заголовок\nіз адмінки')
  await clickText('button','Опублікувати зміни')
  await until("document.body.innerText.includes('Зміни опубліковано')")
  const database=environment.unauthenticatedContext().firestore()
  assert.equal((await getDoc(doc(database,'site','main'))).data().content.texts['hero.title'],'Тестовий заголовок\nіз адмінки')
  console.log('PASS: owner login and text publication')
  await clickText('.admin-sidebar button','Про нас')
  const dom=await send('DOM.getDocument')
  const file=await send('DOM.querySelector',{nodeId:dom.root.nodeId,selector:'.admin-panel input[type=file]'})
  await send('DOM.setFileInputFiles',{nodeId:file.nodeId,files:[resolve('public/images/gear.png')]})
  await until("document.querySelector('.admin-image-field input:not([type=file])').value.includes('127.0.0.1:9199')")
  await clickText('button','Опублікувати зміни')
  await until("document.body.innerText.includes('Зміни опубліковано')")
  assert.match((await getDoc(doc(database,'site','main'))).data().content.images['about.image'],/127\.0\.0\.1:9199/)
  console.log('PASS: photo upload to Storage and publication')
  await clickText('.admin-sidebar button','Адміністратори')
  await until("!!document.querySelector('.admin-two-columns')")
  await fill('.admin-two-columns input[type=email]',editorEmail)
  await evaluate("document.querySelector('.admin-panel form').requestSubmit()")
  await until("document.querySelector('.admin-members').innerText.includes('Доступ активний')")
  console.log('PASS: owner assigns an administrator through UI')
  const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false})
  writeFileSync(join(temporaryDirectory,'admin.png'),Buffer.from(shot.data,'base64'))
  await clickText('.admin-actions button','Вийти')
  await until("!!document.querySelector('input[type=email]')")
  await login(editorEmail)
  await clickText('a','Відкрити адмін-панель →')
  await until("!!document.querySelector('.admin-sidebar')")
  assert.equal(await evaluate("document.querySelector('.admin-sidebar').innerText.includes('Адміністратори')"),false)
  await fill('.admin-panel label:nth-of-type(2) textarea','Зміни адміністратора')
  await clickText('button','Опублікувати зміни')
  await until("document.body.innerText.includes('Зміни опубліковано')")
  console.log('PASS: editor publishes without permission to manage administrators')
  await clickText('.admin-sidebar button','Посилання')
  await fill('.admin-panel input[type=url]','https://www.youtube.com/watch?v=M7lc1UVf-VE')
  await fill('.admin-panel label:nth-of-type(2) input','https://www.youtube.com/@YouTube')
  await clickText('button','Опублікувати зміни')
  await until("document.body.innerText.includes('Зміни опубліковано')")
  await navigate('/')
  await until("!!document.querySelector('.watch-button')")
  assert.equal(await evaluate("!!document.querySelector('.video-dialog iframe')"),false)
  await evaluate("document.querySelector('.watch-button').click()")
  await until("!!document.querySelector('.video-dialog[open] iframe')")
  assert.match(await evaluate("document.querySelector('.video-dialog iframe').src"),/^https:\/\/www.youtube-nocookie.com\/embed\/M7lc1UVf-VE\?autoplay=1/)
  assert.equal(await evaluate("document.querySelector('.video-dialog-links a:last-child').href"),'https://www.youtube.com/@YouTube')
  assert.equal(await evaluate("document.body.style.overflow"),'hidden')
  await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27})
  await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27})
  await until("!document.querySelector('.video-dialog')")
  assert.notEqual(await evaluate("document.body.style.overflow"),'hidden')
  await evaluate("document.querySelector('.film-preview').click()")
  await until("!!document.querySelector('.video-dialog[open] iframe')")
  await clickText('button','✕')
  await until("!document.querySelector('.video-dialog')")
  await navigate('/events/freeride-carpathians')
  await until("!!document.querySelector('.video-preview')")
  await evaluate("document.querySelector('.video-preview').click()")
  await until("!!document.querySelector('.video-dialog[open] iframe')")
  await navigate('/admin')
  await until("!!document.querySelector('.admin-sidebar')")
  assert.equal(await evaluate("!!document.querySelector('.video-dialog')"),false)
  console.log('PASS: videos open in a local modal with YouTube/channel links; closing/navigation removes player and unlocks scrolling')

  await clickText('.admin-sidebar button','Історії')
  await until("!!document.querySelector('.admin-route-fields')")
  await clickText('button','Прибрати трек')
  const earthUrl='https://earth.google.com/earth/d/15EABgg-l3xHSvMspAHvlEnrVTPMbXgdO?usp=sharing'
  await fill('.admin-route-fields input[type=url]',earthUrl)
  await fill('.admin-route-fields textarea','Маршрут тестового звіту')
  await clickText('button','Опублікувати зміни')
  await until("document.body.innerText.includes('Зміни опубліковано')")
  assert.equal((await getDoc(doc(database,'site','main'))).data().content.reports[0].route.earthUrl,earthUrl)
  await navigate('/events/freeride-carpathians')
  await until("!!document.querySelector('.earth-route-card')")
  assert.equal(await evaluate("document.querySelector('.earth-route-card').getAttribute('href')"),earthUrl)
  assert.equal(await evaluate("document.querySelector('.route-description').textContent"),'Маршрут тестового звіту')
  assert.equal(await evaluate("!!document.querySelector('.route-report iframe')"),false)
  await navigate('/admin')
  await until("!!document.querySelector('.admin-sidebar')")
  console.log('PASS: per-report Earth route saves and renders without an unsupported iframe')
  await clickText('.admin-sidebar button','Історії')
  await until("!!document.querySelector('.admin-route-fields')")
  await clickText('button','Додати тестовий маршрут')
  await clickText('button','Опублікувати зміни')
  await until("document.body.innerText.includes('Зміни опубліковано')")
  const savedRoute=(await getDoc(doc(database,'site','main'))).data().content.reports[0].route
  assert.equal(savedRoute.demo,true)
  assert.equal(typeof savedRoute.track[0].lat,'number')
  await navigate('/events/freeride-carpathians')
  await until(mapReady)
  await navigate('/admin')
  await until("!!document.querySelector('.admin-sidebar')")
  console.log('PASS: administrator adds and publishes a demo track; public report preserves Mapbox route settings')
  await environment.withSecurityRulesDisabled(async context=>{await deleteDoc(doc(context.firestore(),'admins',editorUid))})
  await until("!document.querySelector('.admin-sidebar') && document.body.innerText.includes('Ваш акаунт ще не має прав')")
  console.log('PASS: revocation removes editing access in the open browser')
  await navigate('/')
  await until("document.querySelector('.hero h1')?.textContent==='Зміни адміністратора'")
  assert.ok((await evaluate("getComputedStyle(document.querySelector('.about')).backgroundImage")).includes('127.0.0.1:9199'))
  assert.deepEqual(errors,[])
  console.log('PASS: public pages display saved text/photo; no runtime errors')
  console.log(`Screenshot: ${join(temporaryDirectory,'admin.png')}`)
  console.log(`Map screenshot: ${join(temporaryDirectory,'demo-route.png')}`)
  console.log(`Login screenshot: ${join(temporaryDirectory,'login.png')}`)
} finally {
  socket?.close();vite.kill();chrome.kill();backend.kill();await environment.cleanup()
}
